### PR TITLE
fix: improve correctness of exits

### PR DESCRIPTION
**Pull request by henryiii**
Changes some raw uses of `exit()` to either `sys.exit` or `raise Exit` from click. Just a correctness fix (unless site.py is not loaded).

### CODE REVIEW

**Comment by joerick** [comment]
Could we use `sys.exit` rather than `raise Exit`? Seems like the former is more universal.

**Comment by henryiii** [comment]
Sure. `sys.exit` really just raises `SystemExit` anyway, so they are about the same.

**Comment by joerick** [comment]
Thanks. I like to keep things stdlib where possible, keeps the codebase more approachable to newcomers :)

**Comment by henryiii** [comment]
If this was The Way™ to do it in Click, I'd say we should use it, because we are using Click, and we should look like other Click programs. But AFAICT, it is not more common or even that advertised. I _think_ the most "normal" way to do it is to call `sys.exit(ClickApp())` and return an int from the app. Click is kind of specialized for chaining calls.

**Comment by henryiii** [comment]
By the way, do you like `sys.exit(1)`, or return 1 and then wrapping the call in `sys.exit`? I'll do the former tonight unless you like the latter.

**Review by joerick — APPROVED** [review]
The `sys.exit` version seems good to me

**Pull request merged**
