### PR TITLE
WIP: Alternate version of #398

### PR DESCRIPTION
**Pull request by henryiii**
Testing removing shell=True for a better solution to #398. Not expected to work right away.

### CODE REVIEW

**Comment by henryiii** [comment]
I don't see why this change causes `shutil.Error: Destination path 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpk68gtxaq\spam-0.1.0-cp37-cp37m-win_amd64.whl' already exists`...

**Comment by Czaki** [comment]
because without `shell =True` PATH variable is ignored and `cibuildwheel` control which python interpreter is used using `PATH` environment variable. 
You can see that it fails when building wheel for python 2.7. (second version) but in wheel name there is python 3. 

From log:
```
Successfully installed 'python2 2.7.18' to C:\cibw\python
Executing nuget actions took 11.22 sec

+ where python

C:\cibw\python\python2.2.7.18\tools\python.exe
C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe
C:\hostedtoolcache\windows\Python\3.7.7\x64\python.exe
C:\ProgramData\Chocolatey\bin\python.exe
+ python --version
Python 3.6.8
```

**Comment by henryiii** [comment]
Ah, yes. This hasn't been changed in 3.8, so I don't think it's likely to be easily fixable. Going to try 1-2 things.

**Comment by YannickJadoul** [comment]
Resolving `PATH` ourselves and turning the first element of the list into an absolute path is over the top, I suppose? It should be possible, but it's probably not worth the effort, I'm guessing.

**Comment by Czaki** [comment]
> Resolving `PATH` ourselves and turning the first element of the list into an absolute path is over the top, I suppose? It should be possible, but it's probably not worth the effort, I'm guessing.

And may be problematic if some of tool call other in subprocess.

**Comment by YannickJadoul** [comment]
> And may be problematic if some of tool call other in subprocess.

Ah, yes, if in that subprocess, the correct environment /`PATH` isn't there inside the subprocess itself, either, there's no use. Scratch that, then.

Another thing, though. It's possible to pass a list of arguments, and still have `shell=True` (demonstrated in the https://bugs.python.org/issue8557 issue mentioned). Does that fix the quoting of the arguments, or does it also do a stupid `' '.join` inside?

**Comment by henryiii** [comment]
> Resolving PATH ourselves and turning the first element of the list into an absolute path is over the top, I suppose?

I was thinking about trying exactly this. Might be too much, though.

> And may be problematic if some of tool call other in subprocess.

I am injecting the PATH into the environment, so the subprocess should be just fine (and might be already, without the PATH added). It's just that the command itself does not repeat the PATH when resolving.

**Comment by henryiii** [comment]
Why is this being joined, actually? Shouldn't `shell=True` still take a list, and shouldn't that list be properly quoted?

**Comment by YannickJadoul** [comment]
> Why is this being joined, actually? Shouldn't `shell=True` still take a list, and shouldn't that list be properly quoted?

Yes, that's what I meant, in my previous comment. I don't know the reasons for joining the strings..

Oh, btw, I've noticed that there are some calls that do need to have `shell` enabled, because we want to be able to chain commands, etc (see macOS's `call`).

**Comment by YannickJadoul** [comment]
( Or, let's just ditch Windows; I've had enough of its quirks and outright bullshit? ;-) )

**Pull request merged**
