### PR TITLE
docs: fix bullets in 1.6.0 release notes

### PR DESCRIPTION
**Pull request by henryiii**
These were not rendering correctly:

Screen Shot 2021-02-06 at 8 49 50 PM

### CODE REVIEW

**Comment by henryiii** [comment]
Actually, @joerick, the last part of 1.9.0 in the docs renders poorly as well:

Screen Shot 2021-02-06 at 11 16 06 PM


Maybe you could try to fix that? I might be able to get to it at some point, but writing a lot currently.

**Comment by joerick** [comment]
Ohh, are these problems in the documentation version? Because it renders fine in the README in Github-

image

**Comment by joerick** [comment]
the second problem referenced will probably be fixed by the new superfences codeblock thingy from #576

**Comment by henryiii** [comment]
> are these problems in the documentation version?

Yep.

**Comment by joerick** [comment]
btw, that pre-commit auto fix is really cool!

**Comment by henryiii** [comment]
Yes it is. Enables me to be lazy and use the web editor sometimes. :)

**Pull request merged**
