### PR TITLE
PyPy 7.3.1

### PR DESCRIPTION
**Pull request by YannickJadoul**
This is still a release candidate, but let's already check if everything works and if we can remove those few workarounds! :-)

### CODE REVIEW

**Comment by YannickJadoul** [comment]
The macOS failure here is reported to the PyPy developers, and they're working on it. Something seems to be wrong with the compilation on macOS 10.14, while our failing builds are on 10.13.

@joerick, up to you to decide whether you want to wait for this to make a release. My expectation is that the release candidate from PyPy will soon (within a few days/week) be fixed and then get released. The final thing then is to have an official PyPy manylinux wheel, but I already have a PR ready for that (cfr. the `yannickjadoul/manylinux2010-pypy_x86_64:7.3.1` docker image I'm using to test the release candidates).

**Comment by YannickJadoul** [comment]
PyPy 7.3.1 has been released! Rebased onto master as well.

Now just waiting for pypy/manylinux#5 to be merged so it can be used in this PR.

@joerick The first three commits are just different release candidates, and temporary use of https://hub.docker.com/r/yannickjadoul/manylinux2010-pypy_x86_64 instead of PyPy's official images. Do you want to keep this history, or should I just remove it (and get rid of the potentially confusing `git blame` of `cibuildwheel/resources/pinned_docker_images.cfg`)?

**Comment by YannickJadoul** [comment]
Oh, annoying detail: in 1.5 months, the PyPy download links from bitbucket.org will die. So I guess we might need to make a small patch release, once there's a new download location for PyPy :-(

**Comment by Czaki** [comment]
> Oh, annoying detail: in 1.5 months, the PyPy download links from bitbucket.org will die. So I guess we might need to make a small patch release, once there's a new download location for PyPy :-(

Maybe add proper message to this PR? Printed on download fail. To allow user understand why it fail.

**Comment by YannickJadoul** [comment]
> Maybe add proper message to this PR? Printed on download fail. To allow user understand why it fail.

That's a good idea. But any idea where I would do so? Just in `install_pypy`?

**Comment by Czaki** [comment]
> That's a good idea. But any idea where I would do so? Just in install_pypy?

I think it is best place.

**Comment by joerick** [comment]
> Oh, annoying detail: in 1.5 months, the PyPy download links from bitbucket.org will die

Is this because they are moving away from Bitbucket?

**Comment by joerick** [comment]
> Do you want to keep this history, or should I just remove it (and get rid of the potentially confusing `git blame` of `cibuildwheel/resources/pinned_docker_images.cfg`)?

In this case it's of questionable value, but I'm starting to think that keeping history is best, on the whole. It shows a thought process, Github provides useful features if we don't force-push (like 'changes since you last viewed'). Up to you, ultimately though!

**Comment by YannickJadoul** [comment]
> Is this because they are moving away from Bitbucket?

Yeah. And because those people from Bitbucket don't even want to provide some kind of archived version of stuff... Grmbl.

I asked on IRC if I could switch to a new one, but:

> <mattip> use the bitbucket ones for another couple of weeks. We are working on getting a CDN in front of buildbot, and making that an https link

> > 
> 
> In this case it's of questionable value, but I'm starting to think that keeping history is best, on the whole. It shows a thought process, Github provides useful features if we don't force-push (like 'changes since you last viewed').

Myeah, true, I like history, but only the clean version. With too many commits, history isn't worth anything either. This change back and forth was really only to test and prepare the single commit in the end.

> Up to you, ultimately though!

I don't agree with that, though, since in the end, you'll still be the main maintainer and might need to look at history. Personally here, I'd just squash things nicely into one commit, but if you want, I'll leave it like this. At any rate, I'll try to be a bit more conservative towards history, in the future ;-)

**Comment by joerick** [comment]
> > Up to you, ultimately though!
> 
> I don't agree with that, though, since in the end, you'll still be the main maintainer and might need to look at history. Personally here, I'd just squash things nicely into one commit, but if you want, I'll leave it like this. At any rate, I'll try to be a bit more conservative towards history, in the future ;-)

I appreciate that! I'll try to remember to squash when I merge this one.

Let's get this in, and then #310, and I think I'll do a release :)

**Comment by YannickJadoul** [comment]
Yeah, sure. just waiting for pypy/manylinux#5. But that's close, I think!

**Comment by YannickJadoul** [comment]
Oh, and I was waiting for that timing to know whether to put a warning as @Czaki suggested, or whether I can already use the new PyPy download links. Do you want this release urgent? I can go poke around a bit?

**Comment by joerick** [comment]
> Do you want this release urgent? I can go poke around a bit?

No rush, I think I'd rather wait for the new Pypy links than do a release that might break within weeks!

**Comment by YannickJadoul** [comment]
pypy/manylinux#5 got merged. Reverted `pinned_docker_images.cfg` back to `pypywheels/manylinux2010-pypy_x86_64`, rebased onto master, and fixed the (initially forgotten) unit test.

So it's just waiting for the new links, now (or putting the warning into place).

**Comment by joerick** [comment]
> So it's just waiting for the new links, now (or putting the warning into place).

Nice! By the way, how did you find out about the bitbucket links going away? I can see the announcements about the move to hepapod but I can't find anything about the bitbucket links dying.

**Comment by YannickJadoul** [comment]
> Nice! By the way, how did you find out about the bitbucket links going away?

Yes, I popped onto the #pypy IRC, and they were going to poke the PSF about it again.

> I can see the announcements about the move to hepapod but I can't find anything about the bitbucket links dying.

BitBucket is dropping support for Mercurial, so that's why they moved in the first place (though heptapod seems have a UI that's a lot saner and faster than BitBucket as well). New Mercurial repositories can already not be created anymore, and by June all existing Mercurial repos will be deleted (yes, you read that correctly, deleted; not even archived!). See https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

On the moving download links, see also https://mail.python.org/pipermail/pypy-dev/2020-April/015924.html, https://mail.python.org/pipermail/pypy-dev/2020-April/015926.html, and https://mail.python.org/pipermail/pypy-dev/attachments/20200413/6a77159f/attachment.html

If you want to release sooner than that, I'd like to implement @Czaki's suggestion, rather than not having PyPy 7.3.1, btw. There are a few fixes I'd like to use myself :-)

**Comment by joerick** [comment]
Figured I might as well speed this along! You okay with this approach, @YannickJadoul ? We can switch back to pypy official links when they appear.

**Comment by YannickJadoul** [comment]
> Figured I might as well speed this along! You okay with this approach, @YannickJadoul ? We can switch back to pypy official links when they appear.

Sure, yes, I think it's a nice out-of-the-box workaround! :-)
Is this also OK for @mattip? Or is the https://downloads.python.org/pypy really almost there?

**Comment by mattip** [comment]
The https://github.com/joerick/cibuildwheel-resources/releases/download/1/pypy2.7-v7.3.1-osx64.tar.bz2 seems like a good solution. The link is almost there but now shows a 404 message.

**Comment by YannickJadoul** [comment]
Alright, thanks, @mattip!

As you see fit, then, @joerick! It's your release schedule, but this seems fine to me :-)

**Comment by mattip** [comment]
News flash: https://downloads.python.org/pypy/ (with the trailing slash) is live.

**Comment by YannickJadoul** [comment]
Amazing! Thanks for the notification, @mattip!

@joerick, I pushed a new commit. Let's see if this works, but if so, we're definitely ready to merge :-)

**Comment by joerick** [comment]
Hahah what timing :)

**Comment by YannickJadoul** [comment]
Wow, I'm also still not used to seeing AppVeyor finish as first CI :smile:

**Pull request merged**
