### PR TITLE
Pin `manylinux2010` images (CPython 2.7 support)

### PR DESCRIPTION
**Pull request by mayeut**
`manylinux2010` dropped CPython 2.7
Use the tag `2021-02-06-3d322a5` which is the last supporting CPython 2.7

### CODE REVIEW

**Comment by mayeut** [comment]
This could be good for a `cibuildwheel 1.9.x LTS` as mentioned in https://github.com/joerick/cibuildwheel/discussions/580#discussioncomment-348485

I'll also open a PR for dropping Python 2.7 altogether.

**Review by YannickJadoul — APPROVED** [review]
Looks good! The 1.9 and backporting might need some further discussion and practicalities sorted out (about how we're going to achieve it, and what's the policy for backporting, etc), but this PR is independent of that. We'll need to pin this anyway :-)

**Comment by YannickJadoul** [comment]
Although, hmmm, wait. Now anyone building only Python 3.6 wheels would also be stuck on old manylinux2010 images?

We could also introduce `CIBW_MANYLINUX_X86_64_IMAGE=python27`, and try detecting whether Python 2.7 is present?

**Comment by henryiii** [comment]
> would also be stuck on old manylinux2010 

Yes. That's the idea behind making this an LTS then moving forward. I was more interested in making 2010 Py3 only, but still supporting 2.7 until it is dropped (or manylinux1 drops 2.7 support ;) ). I really wanted cibuildwheel to match manylinux. I had a discussion opened about it but @mayeut seems to have gone ahead anyway in the next PR.

What do we do now for manylinux 2014?

**Comment by YannickJadoul** [comment]
> What do we do now for manylinux 2014?

I suppose builds with `manylinux2014` fail if Python 2.7 isn't deselected?

**Comment by mayeut** [comment]
> I suppose builds with manylinux2014 fail if Python 2.7 isn't deselected?

Yes, as mentioned in the docs (`Note that manylinux2014 doesn't support builds with Python 2.7 - when building with manylinux2014, skip Python 2.7 using CIBW_SKIP (see example below).`)

> Although, hmmm, wait. Now anyone building only Python 3.6 wheels would also be stuck on old manylinux2010 images?

> We could also introduce CIBW_MANYLINUX_X86_64_IMAGE=python27, and try detecting whether Python 2.7 is present?

@YannickJadoul,

This specific PR is in fact only here to allow things moving forward for everything except `manylinux2010`. If you look at the current situation, everything is stuck right now (unless more manual actions are taken) because the update pipeline is failing.
This only fixes this situation to allow everything else to update correctly. The points you are raising are valid but might be addressed later on.


> I was more interested in making 2010 Py3 only, but still supporting 2.7 until it is dropped (or manylinux1 drops 2.7 support ;) ). I really wanted cibuildwheel to match manylinux. I thought there was open discussion about it but @mayeut seems to have gone ahead anyway in #596.

@henryiii, I'm happy to discuss again the different options in #596 and I'll expand on that in that issue.

**Review by henryiii — APPROVED** [review]
This is a minimal required step to keep moving forward for 1.9.x. I think it's a no-brainer. :)

**Comment by mayeut** [comment]
Let's merge then.

**Pull request merged**
