### PR TITLE
Update pinned_docker_images.cfg after the ppc64le manylinux2014 image is built again on Travis CI

### PR DESCRIPTION
**Pull request by YannickJadoul**
See also pypa/manylinux#758 and pypa/manylinux#766

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Not sure if this is worth a patch release, actually; up to you @joerick!

**Comment by joerick** [comment]
Great, thank you! Yeah I'll cut a new release with this.

**Comment by YannickJadoul** [comment]
> Great, thank you! Yeah I'll cut a new release with this.

Potentially, we could also wait until PyPy 7.3.2 is released?

**Comment by joerick** [comment]
Ah, just pushed it! I can do another when that lands.

**Pull request merged**
