### PR TITLE
Add Gitlab CI

### PR DESCRIPTION
**Pull request by joerick**
See #158. This PR can be somewhere we can collaborate to see if Gitlab CI is feasible.

### CODE REVIEW

**Comment by joerick** [comment]
That's the tests passing on Linux. Next up, Windows, then we'll need some sample configs.

**Comment by Czaki** [comment]
looking here https://gitlab.com/gitlab-org/ci-cd/shared-runners/images/gcp/windows-containers it looks like chocolatey is installed so configuration based on travis may work.

**Comment by henryiii** [comment]
Also should update the table at the front. :)

**Comment by YannickJadoul** [comment]
Wait, that's al!l? So everything already worked, and this is just adding a CI config?? NICE!

> Also should update the table on the main page. :)

Maybe an example configuration as well?

**Comment by henryiii** [comment]
Was assuming that was already planned:

> then we'll need some sample configs.

**Comment by Czaki** [comment]
> Wait, that's al!l? So everything already worked, and this is just adding a CI config?? NICE!

It means that software is enough god. I think that text 

> `cibuildwheel` is here to help. `cibuildwheel` runs on your CI server - currently it supports Azure Pipelines, Travis CI, AppVeyor, GitHub Actions and CircleCI - and it builds and tests your wheels across all of your platforms. 

should be changed to something like

> `cibuildwheel` is here to help. `cibuildwheel` runs on your CI server - currently it is **tested** on Azure Pipelines, Travis CI, AppVeyor, GitHub Actions and CircleCI - and it builds and tests your wheels across all of your platforms.

**Comment by YannickJadoul** [comment]
> It means that software is enough god. I think that text

Yes, that's what I meant. I'm not sure whether this has already happened before.

> > `cibuildwheel` is here to help. `cibuildwheel` runs on your CI server - currently it supports Azure Pipelines, Travis CI, AppVeyor, GitHub Actions and CircleCI - and it builds and tests your wheels across all of your platforms.
> 
> should be changed to something like
> 
> > `cibuildwheel` is here to help. `cibuildwheel` runs on your CI server - currently it is **tested** on Azure Pipelines, Travis CI, AppVeyor, GitHub Actions and CircleCI - and it builds and tests your wheels across all of your platforms.

That seems quite tricky to change. "supported" is good enough to me, no? It means "it will probably work here". To me "tested" would kind of means it is supposed to work out of the box on the other platforms, but we just haven't tested it? That feels like a strong claim to make.

**Comment by Czaki** [comment]
> That seems quite tricky to change. "supported" is good enough to me, no? It means "it will probably work here". To me "tested" would kind of means it is supposed to work out of the box on the other platforms, but we just haven't tested it? That feels like a strong claim to make.

Hmm. I'm not sure. It will be nice if users try if `cibuildwheel` works for given CI provider without waiting on our reaction. Then these people could provide configuration to us. Current text suggest that it is not working on other (some time ago there are provider specific tricks for windows).

**Comment by joerick** [comment]
Most people just want to build some wheels, and are OSS projects that can choose their CI provider, so want to know which services cibuildwheel supports. Plus, the requirement to access a docker daemon isn't always easy on CI (see the hoops I had to jump through to get Gitlab working)... so I think the current wording still makes sense.

**Comment by joerick** [comment]
I've been busy figuring out a way to test the example configs - here's what I've come up with. There's a script that pushes a basic example project including all the minimal configs to a branch on this repo, and the CI services kick into action and test that. Then the script generates a snippet of Markdown with status badges for this branch. Here's an example.

**Comment by joerick** [comment]
**Examples test run**

Branch: [example-config-test---gitlab-ci-2020-08-30T11-14-36](https://github.com/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-30T11-14-36)

| Service | Config | Status |
|---|---|---|
| appveyor | examples/appveyor-minimal.yml | [Build status](https://ci.appveyor.com/project/joerick/cibuildwheel/branch/example-config-test---gitlab-ci-2020-08-30T11-14-36) |
| azure-pipelines | examples/azure-pipelines-minimal.yml | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---gitlab-ci-2020-08-30T11-14-36) |
| circle-ci | examples/circleci-minimal.yml | [CircleCI](https://circleci.com/gh/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-30T11-14-36) |
| github | examples/github-minimal.yml | Build |
| travis-ci | examples/travis-ci-minimal.yml | [Build Status](https://travis-ci.org/joerick/cibuildwheel) |

Generated by `bin/run_example_ci_config.py`

**Comment by YannickJadoul** [comment]
Wow! :-O This is really cool, @joerick! :-)
More ways to be lazy and sloppy, and still get caught ;-)

AppVeyor is the PyPy macOS thing again. PyPy should soon have a new release, I thought. I'll be sure to create a PR when that happens :-)
And CircleCI seems fixable:
> The script cibuildwheel is installed in '/Users/distiller/Library/Python/3.7/bin' which is not on PATH.

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---gitlab-ci-2020-08-31T18-34-10](https://github.com/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T18-34-10)
> 
> | Service | Config | Status |
> |---|---|---|
> | appveyor | `examples/appveyor-minimal.yml` | [Build status](https://ci.appveyor.com/project/joerick/cibuildwheel/branch/example-config-test---gitlab-ci-2020-08-31T18-34-10) |
> | azure-pipelines | `examples/azure-pipelines-minimal.yml` | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---gitlab-ci-2020-08-31T18-34-10) |
> | circle-ci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T18-34-10) |
> | github | `examples/github-minimal.yml` | [Build](https://github.com/joerick/cibuildwheel/actions) |
> | travis-ci | `examples/travis-ci-minimal.yml` | [Build Status](https://travis-ci.org/joerick/cibuildwheel) |
> | gitlab | `examples/gitlab-minimal.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---gitlab-ci-2020-08-31T18-34-10) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---gitlab-ci-2020-08-31T19-47-23](https://github.com/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T19-47-23)
> 
> | Service | Config | Status |
> |---|---|---|
> | appveyor | `examples/appveyor-minimal.yml` | [Build status](https://ci.appveyor.com/project/joerick/cibuildwheel/branch/example-config-test---gitlab-ci-2020-08-31T19-47-23) |
> | azure-pipelines | `examples/azure-pipelines-minimal.yml` | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---gitlab-ci-2020-08-31T19-47-23) |
> | circle-ci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T19-47-23) |
> | github | `examples/github-minimal.yml` | [Build](https://github.com/joerick/cibuildwheel/actions) |
> | travis-ci | `examples/travis-ci-minimal.yml` | [Build Status](https://travis-ci.org/joerick/cibuildwheel) |
> | gitlab | `examples/gitlab-minimal.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---gitlab-ci-2020-08-31T19-47-23) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---gitlab-ci-2020-08-31T20-03-39](https://github.com/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T20-03-39)
> 
> | Service | Config | Status |
> |---|---|---|
> | appveyor | `examples/appveyor-minimal.yml` | [Build status](https://ci.appveyor.com/project/joerick/cibuildwheel/branch/example-config-test---gitlab-ci-2020-08-31T20-03-39) |
> | azure-pipelines | `examples/azure-pipelines-minimal.yml` | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---gitlab-ci-2020-08-31T20-03-39) |
> | circle-ci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-08-31T20-03-39) |
> | github | `examples/github-minimal.yml` | [Build](https://github.com/joerick/cibuildwheel/actions) |
> | travis-ci | `examples/travis-ci-minimal.yml` | [Build Status](https://travis-ci.org/joerick/cibuildwheel) |
> | gitlab | `examples/gitlab-minimal.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---gitlab-ci-2020-08-31T20-03-39) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by joerick** [comment]
slight snag- the Windows Gitlab test isn't actually passing:
image

**Comment by YannickJadoul** [comment]
Huh, luckily you still included this new testing facility in this PR, then!

Is `$PYTHON` non-empty in the job?

**Comment by joerick** [comment]
I've worked around that specific problem, but there are at least two more...

- [this build](https://gitlab.com/joerick/cibuildwheel/-/jobs/714690553) shows that it doesn't seem to know what the 'echo' command is ([apparently](https://superuser.com/questions/1084349/where-is-the-echo-command-file-found) it's normally a built-in on windows, but that same test passes on the other platforms so I'm unconvinced that I should change it for this case)
- [this example build](https://gitlab.com/joerick/cibuildwheel/-/jobs/714653328#L715) shows that the image is also missing a required toolchain for PyPy - MSVC 14.1... here I'm unsure how to get hold of that toolchain

I'm starting to feel I'm on the edge of an Unknown Amount of Windows Debugging, and given I have no use for Gitlab support personally, if anyone else is interested in debugging these issues I'd be grateful :) Otherwise, I'm thinking I'll just merge the Linux support and punt the Windows support down the road for somebody else to pick up if they have the time/inclination.

**Comment by YannickJadoul** [comment]
>     * [this example build](https://gitlab.com/joerick/cibuildwheel/-/jobs/714653328#L715) shows that the image is also missing a required toolchain for PyPy - MSVC 14.1... here I'm unsure how to get hold of that toolchain

MSVC 14.1 is apparently Visual Studio 2017. Maybe this is a bug, where VS 2019 is too new to be discovered?

How easy is it to set up tests? Do I need to create access to all CI platforms to do so, and create a GitLab repository, etc? Now that I think about it, it might be nice to document this shortly?

But yes, why not drop it until someone is willing to pick it up. It might just be nice to get this merged :-)
One thing though: can we save the current state of the example you had? Either in some scrap-file in the repo, or in a new issue or so. But at least your debugging work won't be lost ;-)

**Comment by joerick** [comment]
> **Examples test run**
> 
> Branch: [example-config-test---gitlab-ci-2020-09-06T15-59-03](https://github.com/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-09-06T15-59-03)
> 
> | Service | Config | Status |
> |---|---|---|
> | appveyor | `examples/appveyor-minimal.yml` | [Build status](https://ci.appveyor.com/project/joerick/cibuildwheel/branch/example-config-test---gitlab-ci-2020-09-06T15-59-03) |
> | azure-pipelines | `examples/azure-pipelines-minimal.yml` | [Build Status](https://dev.azure.com/joerick0429/cibuildwheel/_build/latest?definitionId=2&branchName=example-config-test---gitlab-ci-2020-09-06T15-59-03) |
> | circle-ci | `examples/circleci-minimal.yml` | [CircleCI](https://circleci.com/gh/joerick/cibuildwheel/tree/example-config-test---gitlab-ci-2020-09-06T15-59-03) |
> | github | `examples/github-minimal.yml` | [Build](https://github.com/joerick/cibuildwheel/actions) |
> | travis-ci | `examples/travis-ci-minimal.yml` | [Build Status](https://travis-ci.org/joerick/cibuildwheel) |
> | gitlab | `examples/gitlab-minimal.yml` | [Gitlab](https://gitlab.com/joerick/cibuildwheel/-/commits/example-config-test---gitlab-ci-2020-09-06T15-59-03) |
> 
> Generated by `bin/run_example_ci_config.py`

**Comment by joerick** [comment]
> How easy is it to set up tests? Do I need to create access to all CI platforms to do so, and create a GitLab repository, etc? Now that I think about it, it might be nice to document this shortly?

Good idea - it's documented in https://github.com/joerick/cibuildwheel/pull/419/commits/c3caa5f26f63e80d40628cf7558fa828bc7f82c6 .  It runs on joerick/cibuildwheel, so access is limited to maintainers, but I think that's okay for now. If we need to widen access later, maybe we could create a Github action to run it via a PR comment or something.

> One thing though: can we save the current state of the example you had?

`git revert c67da48510df552eb0a0084785042e5ff6eda7d6` should restore my attempts. I'll make an issue 'Add Gitlab CI Windows support' so we don't forget.

**Review by YannickJadoul — APPROVED** [review]

**Pull request merged**
