### PR TITLE
Update Python from 3.6.6, 3.7.0 to 3.6.7, 3.7.1 on macOS

### PR DESCRIPTION
**Pull request by mayeut**
many bug fixes including CVE.
c.f. https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-7-final
c.f. https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-1-final

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Thanks a lot for noticing the updates! This should be good, but it seems something's wrong with the Python 3/macOS build on Travis CI.

Are these new versions also available for Linux and Windows, then?

**Comment by YannickJadoul** [comment]
> Are these new versions also available for Windows, then?

Nevermind. I forgot that these were preinstalled and thus updated by AppVeyor...

**Comment by YannickJadoul** [comment]
@mayeut If you want, have a look at #112, which should fix the build issue, making this PR mergeable :-)

**Comment by mayeut** [comment]
I had a similar issue with python3 on travis-ci a while back. I did not have time to investigate until now (I switched to python2). Your fix in #112 seems good.

**Comment by YannickJadoul** [comment]
@mayeut Yeah, I'm expecting the same issue on my next push to my project, so it was worth figuring out either way...

Let's get this merged, then :-)

**Pull request merged**
