### PR TITLE
Add time-machine as working example

### PR DESCRIPTION
**Pull request by adamchainz**

### CODE REVIEW

**Comment by YannickJadoul** [comment]
@adamchainz Mind just adding this to the list at #485? We're making batches of these, these days, as it's more complicated than this PR (i.e., the docs weren't regenerated from this change in the yaml file).

**Comment by henryiii** [comment]
I don't mind PRs either, we can just rerun the generation and then merge. Possibly could even add to the CI at some point.

**Comment by YannickJadoul** [comment]
Oh... maybe the README is missing something, then, though?

> or send a PR, adding your information to `docs/data/projects.yml`.

Sorry, didn't know that was stated there.

**Comment by YannickJadoul** [comment]
> I don't mind PRs either, we can just rerun the generation and then merge. Possibly could even add to the CI at some point.

Right, yes, that would make sense; it's not really indicated in the README that this needs to happen, so the more automatic it would be the better?

**Comment by henryiii** [comment]
It's only a few lines for me to do it:

```bash
gh pr checkout 604
./bin/projects.py docs/data/projects.yml --readme README.md --auth $HOMEBREW_GITHUB_API_TOKEN
git add -u
git commit -m "docs: rerun projects.py"
git push
git switch -
```

(Unless someone leaves "master" as the branch name, then it's a headache...)

**Comment by YannickJadoul** [comment]
> It's only a few lines for me to do it:

That's what I thought, yes. That's why I had suggested the #485 for a full batch. But this is easy enough as well :-)

**Comment by YannickJadoul** [comment]
> (Unless someone leaves "master" as the branch name, then it's a headache...)

Even without GitHub CLI, it's reasonably easy to check out PRs, though: https://gist.github.com/piscisaureus/3342247

**Comment by henryiii** [comment]
I prefer the one simple line, though. :) And it is more of a headache with a matching branch name by hand, too.

PS: you don't need to edit a file to do it by hand.

**Comment by henryiii** [comment]
Oh, I see. That's a pretty nice trick, and Amos think affected by branch name! Filed away.

**Comment by YannickJadoul** [comment]
The disadvantage is that you end up with a detached HEAD and that you don't have the upstream branch to push set (like GH CLI does), but still no need for a one-time remote :-)

**Comment by adamchainz** [comment]
Thanks!

**Pull request merged**
