### PR TITLE
Try removing appveyor_run_with_env.cmd

### PR DESCRIPTION
**Pull request by joerick**
I think it was only really needed for Python 3 < 3.4. This would simplify the windows script, removing the shell/simple_shell stuff.

Let's see if the tests pass...

### CODE REVIEW

**Comment by joerick** [comment]
The Travis failure is in fact the s390 build, which I've noticed is failing quite often with a 'no space on device' error. I'll contact Travis support about it, but I'm thinking we should label that platform <sup>BETA</sup> when we release the next version.

**Comment by mayeut** [comment]
@joerick, maybe the s390x shall be marked as allowed to fail for now.
travis-ci knows about the issue but nothing new on this end: https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/11

**Comment by joerick** [comment]
Looks like this is common complaint for Travis CI.

https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/11

I'm going to keep an eye on that thread, but in the meantime, try setting that platform as 'allow_failures' in a separate PR.

**Comment by joerick** [comment]
haha, thanks @mayeut ! We posted the same thing at the same time :)

**Pull request merged**
