### PR TITLE
Fix command substitution in CIBW_ENVIRONMENT in Linux docker images

### PR DESCRIPTION
**Pull request by YannickJadoul**
See #409

### CODE REVIEW

**Comment by YannickJadoul** [comment]
This one is quite scare to have missed in our tests, though :-|

**Comment by joerick** [comment]
Yikes. A bit embarrassed to have missed this one! Also, a tighter type on `docker.call` would have found it. Maybe those ugly overloads are worth it...

**Comment by joerick** [comment]
Thank you for getting this done so quickly!

**Comment by YannickJadoul** [comment]
> Yikes. A bit embarrassed to have missed this one! Also, a tighter type on `docker.call` would have found it. Maybe those ugly overloads are worth it...

Ah, yes, I hadn't considered types here to provide another way of avoiding this. At any rate, should've also been caught during review ... sorry :-/

**Pull request merged**
