### PR TITLE
Build PR branches only once (for origin branches) and skip docs changes

### PR DESCRIPTION
**Pull request by joerick**
My PR branches get built twice on some CI services (Appveyor, Travis, Github), once for the PR and once for the branch. This disables the branch build, for anything other than master, to save some CI time.

Also, on services that support it, I've disabled docs changes from needing CI runs.

### CODE REVIEW

**Comment by Czaki** [comment]
But I sometimes test in my own repository (development only on one system). So this configuration may introduce additional, obsolete PR.

**Comment by joerick** [comment]
> But I sometimes test in my own repository (development only on one system). So this configuration may introduce additional, obsolete PR.

So you have your own CI services set up on your fork?

**Comment by Czaki** [comment]
> So you have your own CI services set up on your fork?

yes. Github actions are enabled out of box based on .github/workflow directory.

**Comment by joerick** [comment]
Okay, you'd have to enable those yourself by deleting this change if you have a branch that you want test on.

**Comment by YannickJadoul** [comment]
And there isn't a way to ignore PRs coming from the same repo (rather than pushes to branches in the repo)?

**Comment by joerick** [comment]
I don't think so, but I had an idea- you could test your personal branches by raising a PR to your own fork's master branch, rather than upstream master

**Comment by Czaki** [comment]
basing on https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions and https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

In github workflow it maybe something like 

```yaml
jobs:
  test:
  if: github.repository != 'joerick/cibuildwheel' || github.ref == master || github.event_name == 'pull_request'
```

**Comment by joerick** [comment]
Ah, okay, I'll give that a shot.

**Pull request merged**
