### PR TITLE
fix: try to avoid error on CircleCI by avoiding explicit an use of /tmp directly

### PR DESCRIPTION
**Pull request by henryiii**
Trying to see if this helps CircleCI.

Ideally we should refactor temporary directory handling, using the high level interface (TemporaryDirectory) and avoiding direclty using `/tmp` too much.﻿

### CODE REVIEW

**Comment by henryiii** [comment]
Hard to tell, but I think this might fix it. I'd like to refactor all the tmp usage to use TemporaryDirectory and a context manager, I think that might fully fix our CI flakiness about `/tmp`. It would also nicely cleanup after runs and help with thread safety (@Czaki's attempt to thread likely hit the fact that all jobs download to exactly the same `/tmp/python.pkg`?)

**Comment by Czaki** [comment]
>  @Czaki's attempt to thread likely hit the fact that all jobs download to exactly the same `/tmp/python.pkg`

No. My attempts fail because `pip` fail when try to perform two installation at same time. And in contradiction to windows. Current macos python installation method does not allow to install python twice on machine.

**Comment by henryiii** [comment]
Are you sure it wasn't because it was actually because it was the same underlying Python, since python.pkg was the same between two runs?

**Comment by Czaki** [comment]
I first run basic_0 stem, and then, when Python is installed I try to run in parallel other tests.

**Comment by joerick** [comment]
I restarted it once this morning, so that's two runs without issues. The `/tmp/Python.pkg` thing is a relic from the very early days (I was trying to make the paths descriptive (like `/tmp/repaired_wheels`), so the logs would make more sense...)

If we wanted to run builds in parallel, we'd need to create virtualenvs for each build, to properly isolate them. That would add to the run-time, though.

**Review by joerick — APPROVED** [review]

**Comment by joerick** [comment]
Just restarted it again. If this one's green, that's a decent chance we've fixed it 🤞

**Comment by henryiii** [comment]
```
+ Download https://www.python.org/ftp/python/3.7.9/python-3.7.9-macosx10.9.pkg to /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmptu6wfpr5/Python.pkg
+ sudo installer -pkg /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmptu6wfpr5/Python.pkg -target /
installer: Error the package path specified was invalid: '/var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmptu6wfpr5/Python.pkg'.
```

Wow, that's really weird. It worked the first time, unlike before, but not the second. I still think #560 is a very good idea.

**Comment by henryiii** [comment]
For debugging, maybe we can add a `ls -l` to this path to see what it's reporting as when it fails, and if the size is wrong.

**Comment by henryiii** [comment]
I believe we are silently passing exceptions in `download`. It's trying three times, failing, and then instead of raising an error, it just returns as if nothing went wrong (as far as I read it). `download` should report and raise an error if it fails.

**Comment by henryiii** [comment]
Failed:
```
-rw-r--r--  1 distiller  staff  27073838 Jan 25 06:49 /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/tmptilibqdo/Python.pkg
```
This time it gave this error:
```
http.client.IncompleteRead: IncompleteRead(219264 bytes read, 24670021 more expected)
```

Working, on Azure (Python 3.5):
```
-rw-r--r--  1 runner  staff  24874014 Jan 25 14:53 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpgplaqpu4/Python.pkg
+ sudo installer -pkg /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpgplaqpu4/Python.pkg -target /
```

**Comment by henryiii** [comment]
I'd like to refactor a bit eventually, but not needed here yet.

**Pull request closed without merging**
