### PR TITLE
fix: keep stderr and stdout from interleaving

### LINKED ISSUE #587: Output mangled
I made a mistake, and cibuildwheel was very helpful in erroring out (otherwise I would have missed the mistake), but the error message was not at all where I was expecting it:

```
2021-02-10T05:15:42.7037690Z ##[group]Run joerick/cibuildwheel@v1.9.0
2021-02-10T05:15:42.7038170Z with:
2021-02-10T05:15:42.7038500Z   package-dir: .
2021-02-10T05:15:42.7038900Z   output-dir: wheelhouse
2021-02-10T05:15:42.7039250Z env:
2021-02-10T05:15:42.7039620Z   SETUPTOOLS_SCM_PRETEND_VERSION: 
2021-02-10T05:15:42.7040240Z   CIBW_ENVIRONMENT: PIP_ONLY_BINARY=numpy SETUPTOOLS_SCM_PRETEND_VERSION=
2021-02-10T05:15:42.7040790Z   CIBW_TEST_EXTRAS: test
2021-02-10T05:15:42.7041250Z   CIBW_TEST_COMMAND: pytest {project}/tests
2021-02-10T05:15:42.7041760Z   CIBW_TEST_SKIP: pp*macos* *universal2:arm64
2021-02-10T05:15:42.7042170Z   CIBW_BUILD: 
2021-02-10T05:15:42.7042530Z   CIBW_SKIP: cp27-win* pp27-win*
2021-02-10T05:15:42.7042940Z   CIBW_MANYLINUX_I686_IMAGE: 
2021-02-10T05:15:42.7043340Z   CIBW_MANYLINUX_X86_64_IMAGE: 
2021-02-10T05:15:42.7043730Z   CIBW_ARCHS: universal2
2021-02-10T05:15:42.7044100Z ##[endgroup]
2021-02-10T05:16:02.6041070Z 
2021-02-10T05:16:02.6042070Z      _ _       _ _   _       _           _
2021-02-10T05:16:02.6042490Z  ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
2021-02-10T05:16:02.6044500Z [?25l[?25hcibuildwheel: No build identifiers selected: BuildSelector('' - 'cp27-win* pp27-win*')
2021-02-10T05:16:02.6045630Z |  _| | . | | | | | . | | | |   | -_| -_| |
2021-02-10T05:16:02.6046050Z |___|_|___|___|_|_|___|_____|_|_|___|___|_|
2021-02-10T05:16:02.6046300Z 
2021-02-10T05:16:02.6046710Z cibuildwheel version 1.9.0
2021-02-10T05:16:02.6046990Z 
2021-02-10T05:16:02.6047400Z Build options:
2021-02-10T05:16:02.6048170Z   platform: 'macos'
2021-02-10T05:16:02.6049220Z   architectures: {<Architecture.universal2: 'universal2'>}
2021-02-10T05:16:02.6050170Z   before_all: ''
2021-02-10T05:16:02.6050570Z   before_build: None
2021-02-10T05:16:02.6051000Z   before_test: None
2021-02-10T05:16:02.6051900Z   build_selector: BuildSelector('' - 'cp27-win* pp27-win*')
2021-02-10T05:16:02.6052710Z   build_verbosity: 0
2021-02-10T05:16:02.6054370Z   dependency_constraints: DependencyConstraintsPosixPath('/usr/local/Cellar/pipx/0.16.0.0/.cache/427fa552d5b62b6/lib/python3.9/site-packages/cibuildwheel/resources/constraints.txt'))
2021-02-10T05:16:02.6056250Z   environment: ParsedEnvironment(['PIP_ONLY_BINARY=numpy', 'SETUPTOOLS_SCM_PRETEND_VERSION='])
2021-02-10T05:16:02.6056980Z   manylinux_images: None
2021-02-10T05:16:02.6057870Z   output_dir: PosixPath('wheelhouse')
2021-02-10T05:16:02.6058740Z   package_dir: PosixPath('.')
2021-02-10T05:16:02.6060020Z   repair_command: 'delocate-listdeps {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}'
2021-02-10T05:16:02.6062130Z   test_command: 'pytest {project}/tests'
2021-02-10T05:16:02.6062950Z   test_extras: '[test]'
2021-02-10T05:16:02.6063400Z   test_requires: []
2021-02-10T05:16:02.6064340Z   test_selector: TestSelector('*' - 'pp*macos* *universal2:arm64')
2021-02-10T05:16:02.6064800Z 
2021-02-10T05:16:02.6065130Z Here we go!
2021-02-10T05:16:02.6065380Z 
2021-02-10T05:16:02.9515910Z ##[error]Process completed with exit code 1.
2021-02-10T05:16:02.9609080Z Cleaning up orphan processes
```

https://github.com/scikit-hep/boost-histogram/runs/1868826910?check_suite_focus=true

### PR DESCRIPTION
**Pull request by henryiii**
I think this fixes #587.

### CODE REVIEW

**Comment by henryiii** [comment]
Looks like circleCI is still getting the pre-fix test/test_docker_images.py . Odd.

**Comment by YannickJadoul** [comment]
> Looks like circleCI is still getting the pre-fix test/test_docker_images.py . Odd.

We've seen CircleCI act weirdly (or at least different from others) on these kinds of things, before, no? It also didn't restart automatically after closing-reopening.

**Review by YannickJadoul — APPROVED** [review]

**Comment by YannickJadoul** [comment]
Is there a way to check this? If so, this can be merged without further input, I'd say :-)

**Comment by joerick** [comment]
I have seen something similar to this before when I was doing the fold groups work, at the time I thought it was a Github actions bug... I might do a little testing to investigate...

**Comment by joerick** [comment]
I don't believe this PR fixes the problem. See this GHA run:
https://github.com/joerick/gha-testing/runs/1888060360?check_suite_focus=true

These examples try to print interleved stdout/stderr messages. So perfect output would look like:

```
1
stderr 1
2
stderr 2
3
stderr 3
4
stderr 4
...
```

As you can see, regardless of the ways I try to disable output buffering, there are still occasionally problems.

It seems to me that this is an inherent problem within GHA. Or perhaps there's a buffer somewhere that we haven't found the controls for yet?

**Comment by henryiii** [comment]
https://github.community/t/stdout-stderr-output-not-in-correct-order-in-logs/16335

Maybe we could redirect stderr to stdout on GHA? Is there really a difference in GHA? (In fact, is there really a difference in any logging system?)

**Comment by joerick** [comment]
Yeah, we could do that. I actually don't think there's any difference between stdout and stderr on CI. I had implemented something like this when I was working on the fold group stuff. The only snag is that some of our tests understand the difference between out/err. But they could be worked around fairly easily.

btw, in our case, we also have to redirect the subprocesses stderr to stdout.

**Comment by joerick** [comment]
Just doing some tidying of PRs, so closing this one.

A simple fix for this would be to add `2>&1` to our sample configs. But that might just cause confusion. Otherwise, it's a refactoring to direct our logs to only stdout, perhaps just when `CI=1` - and figure out how to manage this in the `print-build-identifier` tests

**Pull request closed without merging**
