### PR TITLE
Update to PyPy 7.3.3

### PR DESCRIPTION
**Pull request by YannickJadoul**
The first release candidate for PyPy 7.3.3 has been released. Preparing for a hopefully painless update :-)

CC @mattip, if interested in our tests.

### CODE REVIEW

**Comment by mattip** [comment]
The windows sysconfig.py install scheme changed from bin/pypy*exe to Scripts/pypy*exe to bring PyPy into line with CPython, but I guess you don't make `virtualenv`s here

**Comment by YannickJadoul** [comment]
> but I guess you don't make `virtualenv`s here

We do, actually, to run the tests of a package. I recall something about symlinks, but let me check.

On another note: in our example CI configurations, we have a line `# PyPy 7.3.2 needs macOS >= 10.14` (and select a recent enough version of the CI macOS images). Do you know if this is still the case for 7.3.3, or is it worth trying this out again?

**Comment by mattip** [comment]
:shrug:

We did fix some things around macOSx building, maybe try it out if it is not too painful?

**Comment by YannickJadoul** [comment]
> > but I guess you don't make `virtualenv`s here
> 
> We do, actually, to run the tests of a package. I recall something about symlinks, but let me check.

We had a workaround (symlinking `Scripts` to point to `bin`), but it seems this was already removed in #304 (the update to PyPy 7.3.1; see [this line of one of the commits](https://github.com/joerick/cibuildwheel/pull/304/commits/d7629ad2b3052ceac5f0fc869b918f4d7868c981#diff-b08a2d8e58cec2d061803bfa16beb5bf36cc7d87e5c142c03bebf9d9d6ecbc87L89), commit d7629ad2b3052ceac5f0fc869b918f4d7868c981).

Any further pointers on what has changed now, or why we didn't have issues with this?

At first glance, I don't see a lot of other "workarounds" left, needed to plug in PyPy instead of CPython :-)
(Maybe the symlink of `python.exe` to `pypy.exe` or `pypy3.exe` to be able to just use `python`; but that's arguably not even a workaround.)

**Comment by mattip** [comment]
> Any further pointers on what has changed now, or why we didn't have issues with this?

This release is meant to be a cleanup and tweaks for the C-API for various packages, there should be no breaking changes.

**Comment by YannickJadoul** [comment]
> On another note: in our example CI configurations, we have a line `# PyPy 7.3.2 needs macOS >= 10.14` (and select a recent enough version of the CI macOS images). Do you know if this is still the case for 7.3.3, or is it worth trying this out again?

> We did fix some things around macOSx building, maybe try it out if it is not too painful?

@mattip, Travis CI just passed on macOS, running 10.13 (https://travis-ci.org/github/joerick/cibuildwheel/jobs/743064327#L17), and CircleCI is also passing, so that does seem to be fixed, as well :-)

**Comment by YannickJadoul** [comment]
Hurray, 7.3.3 was released. Waiting for pypy/manylinux#11 to be merged, before reverting `yannickjadoul/manylinux2010-pypy_x86_64` to `pypywheels/manylinux2010-pypy_x86_64`.

**Comment by YannickJadoul** [comment]
Ready! :-)

**Review by joerick — APPROVED** [review]
LGTM!

**Review by henryiii — APPROVED** [review]
LGTM, too!

**Comment by YannickJadoul** [comment]
Hurray. Thanks, both! Let's merge this, then!

**Pull request merged**
