### PR TITLE
Fix AppVeyor's PyPy failure on finding libffi

### PR DESCRIPTION
**Pull request by YannickJadoul**
Cfr. https://foss.heptapod.net/pypy/pypy/issues/3229 and https://foss.heptapod.net/pypy/pypy/merge_requests/726

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Progress. PyPy 2.7 now works with the fixes. Now waiting for a nightly build of 3.6 and maybe later a release with these fixes.

**Comment by joerick** [comment]
Assuming you don't want to merge this until these fixes are in an official Pypy release?

**Comment by YannickJadoul** [comment]
Hmmm, I don't know. I guess we could ping PyPy again and ask what their short term plans on a patch release?

I actually still need to fix a mistake I made in a PR on f-strings, there, that's probably blocking a release :-| I should get to that this weekend.

**Comment by YannickJadoul** [comment]
Closing, since 7.3.2 is out and can almost be merged (see #430).

**Pull request closed without merging**
