### PR TITLE
use variable instead of '/project' literal

### PR DESCRIPTION
**Pull request by Czaki**
Due to discussion in #410 I suggest to use variable instead of repeat `/project` 7 times.

### CODE REVIEW

**Comment by joerick** [comment]
I understand where you're coming from, but I don't really see the improvement in readability - is this just indirection for the sake of it? i.e. what's the difference between `'/project'` and `project_path`? (except that I would recognise `'/project' in logs, and the other I wouldn't)

**Comment by joerick** [comment]
(I realise I'm being a bit of a jerk, but could be an interesting discussion!)

**Comment by YannickJadoul** [comment]
To be honest, I tried the exact same thing in #410 (even before @Czaki mentioned it), seeing the duplication of all the literals, but then had the same reflection on "Is there any difference between writing this variable and writing the string?". The thing is, it's not a complex or weird string that we'll change.

Then again, I don't have an issue with actually changing it. The one thing I would like, if we do this, is turning it into a `PurePath`, since it semantically is a path (so `PurePath` makes more sense as type, right?).

**Comment by Czaki** [comment]
In general when using constant string in multiple places it is easier to introduce bug in code because of some typo. When there is typo in variable name IDE or flake8 may help. 

> Then again, I don't have an issue with actually changing it. The one thing I would like, if we do this, is turning it into a `PurePath`, since it semantically is a path (so `PurePath` makes more sense as type, right?).

In most place it  is used as string. 
And this line https://github.com/joerick/cibuildwheel/pull/413/files#diff-22075e43d4ff5efd0d10f3dcffdb93aaR105 verify if it is proper path

**Comment by YannickJadoul** [comment]
> In most place it is used as string.

Still, it is a path, so unless it gives a lot of overhead, I'd try it as `PurePath`. Wouldn't that work?

**Comment by YannickJadoul** [comment]
> because of some typo.

That's a good point, though. Just an accidental typo wouldn't be caught!

**Comment by joerick** [comment]
Ah, making it a `PurePath` seems a good reason. Could we rename it to `container_project_path` - to match the other variables that refer to paths inside the container?

**Comment by Czaki** [comment]
And what you think @joerick about introduce same changes to windows and macos?

**Comment by joerick** [comment]
> And what you think @joerick about introduce same changes to windows and macos?

Not all that interested, actually. I quite like the path being `'.'`, and relative, because it makes the logs simpler to read, avoiding CI-specific paths in there.

**Pull request merged**
