### PR TITLE
Adding PEP 518 test, fix 3.5 Python on Windows

### PR DESCRIPTION
**Pull request by henryiii**
As discussed in #350 

I'll fix the flake8 problem after the build. Wish this used pre-commit, I checked `pre-commit run` just to see.

### CODE REVIEW

**Comment by YannickJadoul** [comment]
On the topic of pre-commit, there's a PR pending #347 ;-)

**Comment by henryiii** [comment]
By the way, as predicted, this breaks on Python 3.5.4 + Windows, and works elsewhere!

**Comment by henryiii** [comment]
It is possible this was a fix that went into 3.5.5, but it's really hard to find anything past 3.5.4 on Windows, since Python stopped providing binaries at 3.5.4, while the other platforms may have newer versions. Or it could be completely unrelated to the patches in Python.

**Comment by YannickJadoul** [comment]
Nice! Thanks for clearing this up! :-)

Don't break your head over the Python 3.5 on Windows, though, I'd say. If it seems it's not a cibuildwheel thing, there's not a lot we can do (except report upstream if your debugging is successful, ofc). In a few months, 3.5 is end-of-life anyway, so ...

**Comment by henryiii** [comment]
It's pretty easy to workaround, as well. It would be nice to simply say "3.5+" instead of adding caveats, and for it to work correctly out of the box. 3.5 on Linux is still around in a few places (Ubuntu 16.04, I last saw it on an old Raspbian), but I really doubt anyone is using it on Windows (or macOS).

Pip does check 3.5.4 on Windows in their testing matrix, though, which is quite odd that this is failing. I haven't checked their tests, but I know they at least test PEP 517 (this is technically 518, finally have the difference straight). It looks like on 3.5 + Windows it is not building in the environment pip set up for the build.

**Comment by henryiii** [comment]
This is on a back burner for now for me; I bet it will need to be a report to pip, though, but not sure yet.

**Comment by henryiii** [comment]
TODO: rename the test file 517 -> 518, as that's really what is being tested; the PEP 517 printout by Pip is only because that activates too.

**Comment by YannickJadoul** [comment]
Hmmm, interesting, but quite annoying. If we could somehow pinpoint what goes wrong, we could apply a patch. But apart from that NuGet works quite well across different platforms, so it's probably not worth ditching it to solve this issue.

Is there a point in diffing the stdlib folders or so, between the two distributions?

**Comment by henryiii** [comment]
I've patched for PEP 518 builds on Python 3.5. The problem is that the nuget distribution is based on the Embedded Python build. In 3.5, there wasn't a way to get it to behave like normal Python, and respect `PYTHON*` variables. This breaks pip's PEP 518 mechanism, which manipulates these variables. The embedded Python is not supported by pip (at least in embedded mode, which you can't disable on 3.5), so it's unlikely to be fixed by pip.

A workaround based on a suggestion by core Python and pip developer @pfmoore has been implemented, where the pyproject.toml requirements are injected into the prepared build environment when running Python 3.5 Windows builds. If this was eventually fixed, pip would start using build isolation like it does elsewhere, and the workaround does not affect the isolated environment.

@joerick, there is some flexibility in where this could go - I've added it to the setup function.

**Comment by joerick** [comment]
Thank you for this @henryiii! This seems like a good workaround.

In terms of where it should go, `setup_python` probably isn't quite right, as it's doing stuff with the package. Actually, it should be using `options.package_dir` to find pyproject.toml (right now it's looking for a pyproject.toml in the working dir, but this should be `os.path.join(options.package_dir, 'pyproject.toml')`). So maybe we can create a function `pep_518_cp35_workaround(package_dir, env)` that is called after `setup_python` in the main build function?

**Comment by joerick** [comment]
Thanks again @henryiii !

**Comment by ajfriend** [comment]
This is great. Thanks all!

**Pull request merged**
