### PR TITLE
Use yaml anchors and references to not repeat full job in allow_failures

### PR DESCRIPTION
**Pull request by YannickJadoul**
Minor detail, but I'd still like to see CI pass, rather than pushing to master.

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Random remark: @joerick, mind if we clean up some of your merged branches?
I keep on typing `git checkout ma<tab>`, and it doesn't work, because there's still an ancient `mayeut-patch-1` branch on `upstream` (i.e. `joerick/cibuildwheel`)

**Comment by YannickJadoul** [comment]
> Random remark: @joerick, mind if we clean up some of your merged branches?
> I keep on typing `git checkout ma<tab>`, and it doesn't work, because there's still an ancient `mayeut-patch-1` branch on my `upstream` remote.

(Actually, just noticed. That branch might not be stale, but some other are definitely merged.-

**Comment by joerick** [comment]
Nice! I didn't know YAML could do this

**Comment by joerick** [comment]
I've had a purge of branches - thanks for the reminder

**Comment by YannickJadoul** [comment]
Great, thanks! :-)

**Comment by YannickJadoul** [comment]
@joerick Travis now lists 2 "info messages" on the config, as well:

> - root: missing os, using the default linux
> - language: value minimal is an alias for shell, using shell

Might be worth changing, while we're at it?

**Pull request merged**
