### PR TITLE
Debug CircleCI failures

### PR DESCRIPTION
**Pull request by joerick**
Debugging recent linux circleCI failures

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Haha, you beat me to it. I just wanted to start looking at this.

Seems @Czaki might be right, though, about `poetry` being installed and messing up the installation of `virtualenv`? https://github.com/joerick/cibuildwheel/pull/342#issuecomment-647478067

**Comment by joerick** [comment]
> Seems @Czaki might be right, though, about `poetry` being installed and messing up the installation of `virtualenv`? [#342 (comment)](https://github.com/joerick/cibuildwheel/pull/342#issuecomment-647478067)

Could be... but the install command actually succeeds, despite this error message. Quite confusing...

**Comment by Czaki** [comment]
maybe add `set -e`  to .circleci/prepare.sh

**Comment by joerick** [comment]
> maybe add `set -e` to .circleci/prepare.sh

`set -o errexit` is the same as `set -e`, that's already there.

**Comment by Czaki** [comment]
Ok. I do not notice that it is changed in this PR. Sorry.

**Comment by joerick** [comment]
Alright, think I got it. `virtualenv` is already system-installed on the Docker image, so installing a `--user` version and having multiple versions installed was causing problems. I removed the `--user` version.

**Comment by YannickJadoul** [comment]
> Alright, think I got it. `virtualenv` is already system-installed on the Docker image, so installing a `--user` version and having multiple versions installed was causing problems. I removed the `--user` version.

Pfffffffffffffffffffff, good catch! But horrible error message.

Anyway, it's just our own CI config and nothing in `cibuildwheel`, so whatever makes things green :-)

**Comment by joerick** [comment]
Just testing out a fire-and-forget "merge when green" app.

**Pull request merged**
