### PR TITLE
Separate 'mkdocs_include_markdown_plugin' from documentation

### PR DESCRIPTION
**Pull request by mondeja**
As was discussed in #470, the plugin `mkdocs_include_markdown_plugin` have been separated into new package [mkdocs-include-markdown-plugin](https://pypi.org/project/mkdocs-include-markdown-plugin/).

### CODE REVIEW

**Review by joerick — APPROVED** [review]
Cheers @mondeja !

**Comment by YannickJadoul** [comment]
Great, let's merge this! :-)

@mondeja, one more small thing: how much time will you have to maintain the package? I'm just thinking we will now depend on this project that used to be vendored. Of course we can make a PR if necessary, but just curious/hoping to hear that that would then get merged soon enough? :-)

It's just that I'm seeing talks in #474 about including different parts from the README, and I realized we won't have full control anymore over this plugin in the rare case something needs to be changed. But all of that is fine if you'll have enough time. If at some point you don't, do please let us know! It would be sad to see the project go.

(Also, depends a bit on what @joerick would want, but since it's his brainchild, I guess you could add him as "passive maintainer"?)

**Comment by mondeja** [comment]
> how much time will you have to maintain the package?

Don't worry, every day I help with the maintenance of several open source projects that I need both in my work and in my individual projects, and I don't like unmaintained projects at all, so I am aware of what it means, being usually operational for revisions 95% of the days of the year. I'm sure that if you open a pull request, since the plugin now contains tests, they will be easy to review.

> I guess you could add him as "passive maintainer"?

Just let me know if one of more of you want to be added as maintainers with full permissions, both for the project in PyPI and the Github repository.

**Comment by YannickJadoul** [comment]
OK, thanks for quickly setting my mind at ease! :-)

Given that @joerick already approved, let's get this merged. Thanks a lot for the initiative, @mondeja!

**Pull request merged**
