### PR TITLE
clean after bump to pypy 7.3.1

### PR DESCRIPTION
**Pull request by Czaki**
I realize that some cleaning are not done in #304

### CODE REVIEW

**Comment by YannickJadoul** [comment]
Ah, good catch. I thought I had looked, but forgot about those!

**Comment by Czaki** [comment]
Ready.

**Comment by YannickJadoul** [comment]
Rerunning failed `ppc64le` (though there's no chance it's actually broken).

**Comment by Czaki** [comment]
pasaed

**Pull request merged**
