### PR TITLE
Add support for Windows on CircleCI

### LINKED ISSUE #381: Add CircleCI support for Windows
CircleCI now supports Windows (including on the free plan)
https://circleci.com/docs/2.0/hello-world-windows/#prerequisites

### PR DESCRIPTION
**Pull request by YannickJadoul**
Closes #381

### CODE REVIEW

**Comment by Czaki** [comment]
hm. Maybe @joerick needs to do something on his account. 
obraz

**Comment by YannickJadoul** [comment]
@ixje I'm also finding the "Either the Free plan (default) or a performance plan." line in the docs, but the Windows build fails with the following error message:

image

Any idea why?

**Comment by YannickJadoul** [comment]
> hm. Maybe @joerick needs to do something on his account.

Yes, I'm on it. I'm still busy with this PR and was writing something.

**Comment by joerick** [comment]
This is the state of my account... hmmm....

image

might have to get in touch with support!

**Comment by YannickJadoul** [comment]
https://support.circleci.com/hc/en-us/articles/360046351354-When-will-my-free-credits-refill-

So it seems that free accounts have a number of credits?
And maybe these are ignored for OSS projects? https://circleci.com/open-source/ only lists Linux and macOS, though, so that's probably why.

So, I can probably contact them, and maybe they'd still grant us access or credits to Windows (since our FOSS (!!) tool would support their software), but is there any point if other OSS project can't use them?

**Comment by joerick** [comment]
I've contacted CircleCI. They were pretty good about enabling macOS builds, so hopefully the same will be true here.

**Comment by YannickJadoul** [comment]
> I've contacted CircleCI. They were pretty good about enabling macOS builds, so hopefully the same will be true here.

Great, thanks! :-)

To be entirely honest, even if they make an exception for us, I'm not sure I'm super happy adding and maintaining support in `cibuildwheel` for a feature that cannot be used by other open source projects, though. We're not some kind of charity developing software tools for companies for free (with all respect for @ixje, and his kind enthusiasm about `cibuildwheel`, letting us know about Windows builds on CircleCI :-) )

**Comment by ixje** [comment]
Let's hope they just forgot to match the toggle with the documentation and that this reachout will enable it for all, not just for paid plans. 🙏

**Comment by Czaki** [comment]
> To be entirely honest, even if they make an exception for us, I'm not sure I'm super happy adding and maintaining support in `cibuildwheel` for a feature that cannot be used by other open source projects, though. We're not some kind of charity developing software tools for companies for free (with all respect for @ixje, and his kind enthusiasm about `cibuildwheel`, letting us know about Windows builds on CircleCI :-) )

If i good understand documentation and information from screens it is available for free but not in such amount of credits which are needed by this project. 

And also it may depend of number of hours needed form maintenance.

**Comment by joerick** [comment]
From CircleCI:

> Windows is currently only available for customers on Performance pricing. We are working on making Windows available for FOSS projects building under a free plan, but for now we don’t have a specific date for when that will be ready.

> For FOSS customers who would like to build on Windows today, we suggest upgrading to the Performance plan. This is a usage-based plan that starts at $30/month, $15 per 25,000 credits + $15 for the first 3 users ($15 per user thereafter). This plan also makes available configurable resource class and scalable concurrency and parallelism. One caveat is that the free open source credits cannot be applied on the Performance Plan, so all projects will consume paid credits.

> If you're interested in learning and discussing more about the Performance Plan, please let me know and I can put you in touch with an account representative to offer further details!

**Comment by YannickJadoul** [comment]
Well, then don't advertise it!?
So not even an offer for an exception for this project? They're not expecting we're going to pay for an open source project to support their paid CI, are they? :-D

**Comment by YannickJadoul** [comment]
At any rate, @ixje: I'm suspecting CircleCI might work out of the box (or with minimal adaptations), since both CircleCI's macOS and Linux, as well as Windows CI providers are already supported. So if you want to try, feel free to take this code (and even contact me for specific problems), but we can't support a system we don't have access to, unfortunately :-/

Thanks for notifying us of the existence, though! :-) Maybe in a few months/years we will be able to support this.

**Comment by YannickJadoul** [comment]
(Oh, and thanks for contacting them, @joerick! ;-) )

**Comment by ixje** [comment]
Yikes, what a poor response. Thanks for giving it a try @YannickJadoul @joerick

**Comment by ixje** [comment]
FYI; it does seem to work on a free account. Once my credits refill (or if I get permission to use my organisations plan) I will try to finalise the config. I guess SSH debugging eats credits like mad O_o

**Pull request closed without merging**
