### PR TITLE
Update dependencies and fix pypy setuptools bug on downgrade

### PR DESCRIPTION
**Pull request by joerick**
Update the versions of our dependencies.

PR generated by `make_dependency_update_pr.py`.

### CODE REVIEW

**Comment by joerick** [comment]
Hmm, getting this error again :

> ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\cibw\\pypy3.6-v7.3.0-win32\\scripts\\easy_install.exe'

...when downgrading setuptools from 46.1.3 to 46.0.0 on `pypy3.6-v7.3.0-win32`

https://github.com/joerick/cibuildwheel/pull/310/checks?check_run_id=564011984#step:6:1299

I had thought that 13554d0490467bceadee124b32ad304596e907d5 fixed this, but I guess not...

**Comment by joerick** [comment]
I now have access to a Windows VM, I'll try to get a minimal recreation for the pypy folks.

**Comment by YannickJadoul** [comment]
Oh, no, this kind of stuff again.

Could it have something to do with the symbolic link from `Scripts` to `bin`? Windows seems to be acting weirdly with these symbolic links sometimes; I ran into a weird error message when trying out the release candidate for PyPy 7.3.1, where the `bin` folder on Windows was fixed to `Scripts` making the `mklink /d` command wrong (but somehow Windows doesn't warn about that).

I just downloaded `pypy3.6-v7.3.0-win32.zip`. Could this have something to do with the `bin` folder not being there, at first (and thus the `Scripts` symbolic link pointing to a non-existing directory) ?

**Comment by joerick** [comment]
> Could it have something to do with the symbolic link from `Scripts` to `bin`?

This was my thought as well... investigating now!

**Comment by Czaki** [comment]
> > Could it have something to do with the symbolic link from `Scripts` to `bin`?
> 
> This was my thought as well... investigating now!

Maybe add both bin and Scripts to path?

**Comment by joerick** [comment]
> Could it have something to do with the symbolic link from `Scripts` to `bin`?

```
c:\pypy3.6-v7.3.0-win32>pypy3.exe -m pip install setuptools==46.0.0
Requirement already satisfied: setuptools==46.0.0 in .\site-packages (46.0.0)

c:\pypy3.6-v7.3.0-win32>pypy3.exe -m pip install setuptools==46.1.0
Collecting setuptools==46.1.0
  Using cached setuptools-46.1.0-py3-none-any.whl (582 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 46.0.0
    Uninstalling setuptools-46.0.0:
      Successfully uninstalled setuptools-46.0.0
  WARNING: The scripts easy_install-3.6.exe and easy_install.exe are installed in 'c:\pypy3.6-v7.3.0-win32\bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed setuptools-46.1.0

c:\pypy3.6-v7.3.0-win32>pypy3.exe -m pip install setuptools==46.0.0
Collecting setuptools==46.0.0
  Using cached setuptools-46.0.0-py3-none-any.whl (582 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 46.1.0
    Uninstalling setuptools-46.1.0:
      Successfully uninstalled setuptools-46.1.0
  WARNING: The scripts easy_install-3.6.exe and easy_install.exe are installed in 'c:\pypy3.6-v7.3.0-win32\bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed setuptools-46.0.0

c:\pypy3.6-v7.3.0-win32>mklink /d c:\pypy3.6-v7.3.0-win32\Scripts c:\pypy3.6-v7.3.0-win32\bin
symbolic link created for c:\pypy3.6-v7.3.0-win32\Scripts <<===>> c:\pypy3.6-v7.3.0-win32\bin

c:\pypy3.6-v7.3.0-win32>pypy3.exe -m pip install setuptools==46.1.0
Collecting setuptools==46.1.0
  Using cached setuptools-46.1.0-py3-none-any.whl (582 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 46.0.0
    Uninstalling setuptools-46.0.0:
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\pypy3.6-v7.3.0-win32\\scripts\\easy_install.exe'

```

Yeah, this looks to be the culprit. Maybe I'll try the SYMLINKS_DIR approach we use over on the Mac.

**Comment by YannickJadoul** [comment]
> > > Could it have something to do with the symbolic link from `Scripts` to `bin`?
> > 
> > 
> > This was my thought as well... investigating now!
> 
> Maybe add both bin and Scripts to PATH?

Not sure I would do that, actually. `bin` is PyPy-specific, so that feels a bit like a hack.

You could try with the latest 7.3.1 release candidates (cfr #304), though, @joerick? PyPy 7.3.1 is almost released and uses `Scripts`, so there's not reason to put a lot of time into fixing this if the problem is soon solved, anyway.

**Comment by joerick** [comment]
Good idea! I'll give that a shot.

**Comment by YannickJadoul** [comment]
(Just to be sure: mind the temporary change I made to `pinned_docker_images.cfg`, btw, to try the PyPy docker image without making a PR for them yet. I didn't update `update_dependencies.py`, though.)

**Comment by joerick** [comment]
Looks good! Thanks @YannickJadoul for the prompt - I hadn't realised that was fixed in 7.3.1. I'll hold off on this dependency update until your PR gets merged.

Given the underlying issue in PyPy, I'll hold off on another release until then too.

**Comment by YannickJadoul** [comment]
Uuuuh, it works now? OK, slightly annoying we don't know what's up with the symlink, but ... good that it's fixed! :-)

I'm updating the PR the moment PyPy 7.3.1 gets released. Should be no more than a week, I think.

**Comment by Czaki** [comment]
Get-pip start tagging releases:
https://github.com/pypa/get-pip/tree/20.1

https://github.com/pypa/get-pip/issues/56

**Comment by joerick** [comment]
> Get-pip start tagging releases:
> https://github.com/pypa/get-pip/tree/20.1
> 
> [pypa/get-pip#56](https://github.com/pypa/get-pip/issues/56)

This is useful, we should remember for the next time we want to update get-pip. But I don't think we need to do it now.

Also relevant - I noticed that [Homebrew](https://brew.sh)'s install instructions use a raw.githubusercontent.com URL, and that must get a _ton_ of traffic. If it works for them, I'm guessing it'll work for us too.

**Comment by joerick** [comment]
Closed in favour of #332

**Pull request closed without merging**
