### PR TITLE
Replace get-pip.py by ensurepip module

### PR DESCRIPTION
**Pull request by YannickJadoul**
Let's check again if `get-pip.py` could be replaced by `ensurepip` to bootstrap pip.

### CODE REVIEW

**Comment by henryiii** [comment]
FYI, I think pip is included in the nuget distributions already, so you would only need to upgrade, and would not need ensurepip.

**Comment by YannickJadoul** [comment]
Ah, thanks! I should have another look. I got disheartened by the failing builds and gave up on debugging.

**Comment by joerick** [comment]
Closing to tidy things up. Feel free to reopen if you're still working on it!

**Comment by YannickJadoul** [comment]
> Closing to tidy things up. Feel free to reopen if you're still working on it!

Yep, sorry! Currently no time, and not near the top of my TODO-stack anymore, but still something I'd like to pursue :-)

**Pull request closed without merging**
