### PR TITLE
Better help for GitHub Actions + Py27 workaround

### PR DESCRIPTION
**Pull request by henryiii**
Mentioned in #333 discussion.

### CODE REVIEW

**Comment by henryiii** [comment]
Also see https://github.com/microsoft/setup-msbuild/issues/13 - setup-msbuild is very specifically only a way to setup msbuild and not the rest of the env variables needed by distutils.

**Comment by YannickJadoul** [comment]
Oops, sorry! I should have looked better, when adding that :-(

Does this work better, perhaps? https://github.com/ilammy/msvc-dev-cmd
I can't believe MS doesn't have a better way to set up the environment :-|

**Comment by YannickJadoul** [comment]
> Does this work better, perhaps? https://github.com/ilammy/msvc-dev-cmd
> I can't believe MS doesn't have a better way to set up the environment :-|

**Comment by YannickJadoul** [comment]
Sorry, wanted to comment but misclicked...

Was going to say I'd try myself, but I've not set up a GitHub Actions CI before, so it might be faster if you can try.

**Comment by henryiii** [comment]
I can test that, I'm writing up docs anyway. They do mention the idea of having a setup action in the issue above, but they don't have one yet.

**Comment by YannickJadoul** [comment]
Great, thanks! I'm really baffled there seems to be no official way to "activate" Visual Studio in GitHub Actions?

I also propose to maybe at the example code as a separate file to `examples/`, and just link to it? If we add this amount of example code for everything (i.e., not just for GitHub Actions, but also for Travis CI, etc), things might become messy.

**Comment by henryiii** [comment]
Here's the example snippet:

```yaml
  - uses: ilammy/msvc-dev-cmd@v1

  - name: Build 64-bit wheel
    run: python -m cibuildwheel --output-dir wheelhouse
    env:
      CIBW_BUILD: cp27-win_amd64
      DISTUTILS_USE_SDK: 1
      MSSdk: 1

  - uses: ilammy/msvc-dev-cmd@v1
    with:
      arch: x86

  - name: Build 32-bit wheel
    run: python -m cibuildwheel --output-dir wheelhouse
    env:
      CIBW_BUILD: cp27-win32
      DISTUTILS_USE_SDK: 1
      MSSdk: 1
```

Only saw a minimal example, so didn't change that.

**Comment by YannickJadoul** [comment]
@joerick Good to merge, if it's up to me. But maybe you want to have a say on whether and how to include the example?

**Comment by joerick** [comment]
This looks good - would it also be appropriate to include that snippet after the `illamy` bullet point?

**Comment by henryiii** [comment]
You mean the example snippet? I'd be happy to include it but wan't sure if it fit, since it's GHA only.

Is there a way to access `<details><summary></summary></details>` in the docs? That would be ideal :)

**Comment by henryiii** [comment]
Added the snippet back in.

**Comment by henryiii** [comment]
One travis build stalled, feel free to restart (or ignore, since this is documentation only).

**Comment by joerick** [comment]
Thank you @henryiii!

**Pull request merged**
