### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by henryiii**
Update the versions of our dependencies.

PR generated by `make_dependency_update_pr.py`.

See #487.

### CODE REVIEW

**Comment by henryiii** [comment]
Does this update macOS / windows downloads? Seems like we should be on 3.9.1 now.

**Comment by YannickJadoul** [comment]
> Does this update macOS / windows downloads?

Nope, those were never part of this file, I believe.

**Comment by henryiii** [comment]
Bumped those by hand. 3.7.9, 3.8.6 and 3.9.1 all have binaries.

**Review by joerick — APPROVED** [review]
LGTM!

**Comment by henryiii** [comment]
@mayeut feel free to merge this as soon as you are done with the PR creation bot PR. It likely will be harder to test that after this is merged.

**Comment by mayeut** [comment]
Thanks @henryiii.
There's been an update to `setuptools` that will allow to test some more if needed so merging this now if @joerick wants to release 1.7.2

**Comment by joerick** [comment]
1.7.2 released!

**Pull request merged**
